create table if not exists public.wallet_heroes (
  id bigint generated by default as identity primary key,
  wallet_address text not null,
  hero_id text not null,
  chain_id integer not null
);

alter table public.wallet_heroes
  add column if not exists chain_name text,
  add column if not exists class_id integer,
  add column if not exists class_name text,
  add column if not exists level integer,
  add column if not exists rarity_id integer,
  add column if not exists rarity_name text,
  add column if not exists generation integer,
  add column if not exists is_gen0 boolean not null default false,
  add column if not exists influence_score numeric,
  add column if not exists influence_value numeric,
  add column if not exists summons_remaining integer,
  add column if not exists eligible boolean not null default false,
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists index_status text not null default 'pending',
  add column if not exists source text,
  add column if not exists discovered_at timestamptz not null default now(),
  add column if not exists last_seen_at timestamptz,
  add column if not exists indexed_at timestamptz,
  add column if not exists index_error text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.wallet_heroes'::regclass
      and conname = 'wallet_heroes_wallet_address_hero_id_chain_id_key'
  ) then
    alter table public.wallet_heroes
      add constraint wallet_heroes_wallet_address_hero_id_chain_id_key
      unique (wallet_address, hero_id, chain_id);
  end if;
end $$;

create index if not exists idx_wallet_heroes_wallet
  on public.wallet_heroes (wallet_address);

create index if not exists idx_wallet_heroes_wallet_chain
  on public.wallet_heroes (wallet_address, chain_id);

create index if not exists idx_wallet_heroes_gen0
  on public.wallet_heroes (wallet_address, is_gen0)
  where is_gen0 = true;

create index if not exists idx_wallet_heroes_index_status
  on public.wallet_heroes (index_status, last_seen_at);

create index if not exists idx_wallet_heroes_pending_wallet
  on public.wallet_heroes (wallet_address, index_status)
  where index_status in ('pending', 'queued', 'failed');
