create table if not exists public.wallet_heroes (
  id bigint generated by default as identity primary key,
  wallet_address text not null,
  hero_id text not null,
  chain_id integer not null,
  chain_name text,
  class_id integer,
  class_name text,
  level integer,
  rarity_id integer,
  rarity_name text,
  generation integer,
  is_gen0 boolean not null default false,
  influence_score numeric,
  influence_value numeric,
  summons_remaining integer,
  eligible boolean not null default false,
  updated_at timestamptz not null default now(),
  unique(wallet_address, hero_id, chain_id)
);

create index if not exists idx_wallet_heroes_wallet
  on public.wallet_heroes (wallet_address);

create index if not exists idx_wallet_heroes_wallet_chain
  on public.wallet_heroes (wallet_address, chain_id);

create index if not exists idx_wallet_heroes_gen0
  on public.wallet_heroes (wallet_address, is_gen0)
  where is_gen0 = true;
